### ISSUE TITLE
Support for searching titles in translated languages

### ISSUE THREAD

**Issue by Primdahl26** [streamchaser/streamchaser#107]
### Is your feature request related to a problem? Please describe.

I would like it so that you can search for movie/tv shows. So for an example to find `Lord of the rings` you would have to type `Lord of the rings`. But in danish the movie would be called `Ringenes herre`. 

This would be possible using: https://developers.themoviedb.org/3/getting-started/languages 

The issue lies in that we would need to make additional 4 API calls pr media, unless we can figure something smart out?

### Describe the solution you'd like

Find a way with minimal extra api calls to TMDB where we can get the above described.

**Comment by AndreasPB** [comment]
https://api.themoviedb.org/3/movie/120?api_key=<api_key>&append_to_response=translations
