### ISSUE TITLE
Cronjob to use TMDB changes

### ISSUE THREAD

**Issue by Primdahl26** [streamchaser/streamchaser#117]
### Is your feature request related to a problem? Please describe.

Right now the daily cronjob runs through all are elements in the DB and this takes around 1,5 hours. 

### Describe the solution you'd like

This is unnecessary since we can use https://developers.themoviedb.org/3/changes/get-movie-change-list and https://developers.themoviedb.org/3/changes/get-tv-change-list. 
 
If `change` does not include new `id`s we need some logic to handle still getting new `id`s, so we don't end up not getting new movies and tv shows.

**Comment by AndreasPB** [comment]
https://api.themoviedb.org/3/movie/changes?api_key=<tmdb-key>&start_date=2022-03-10&page=1

**Comment by nullxDEADBEEF** [comment]
Related #230

**Comment by AndreasPB** [comment]
This can probably be closed when #222 is merged. #230 is for handling the next step
