### ISSUE TITLE
Update Svelte Multiselect

### ISSUE THREAD

**Issue by Primdahl26** [streamchaser/streamchaser#128]
### Is your feature request related to a problem? Please describe.

Right now we cannot use new versions of [Svelte Multiselect](https://github.com/janosh/svelte-multiselect). 

We need to handle this properly: https://github.com/janosh/svelte-multiselect/releases/tag/v2.0.0

### Describe the solution you'd like

Id like a solution where we kill the weird dict methods we use for our genres. This should also allow us to update the multi selects, when we handle them as objects.

**Comment by Pankai222** [comment]
Use of Svelte Multiselect has been dropped in favor of [Svelte Select](https://github.com/rob-balfre/svelte-select)

**Comment by AndreasPB** [comment]
Fixes #17

**Comment by AndreasPB** [comment]
Closes #17
