### ISSUE TITLE
Setup Grafana Cloud

### ISSUE THREAD

**Issue by AndreasPB** [streamchaser/streamchaser#165]
### Is your feature request related to a problem? Please describe.

It would be nice to not have to SSH in to watch logs/metrics

### Describe the solution you'd like

Setup Grafana Cloud

### Additional context

https://grafana.com/products/cloud/

**Comment by AndreasPB** [comment]
Ping me somewhere for an example of how the docker-compose should look like

**Comment by nullxDEADBEEF** [comment]
This issue has been handled in #196
