### ISSUE TITLE
Populate content of cast/tv/movie grids on details views from the center

### ISSUE THREAD

**Issue by Pankai222** [streamchaser/streamchaser#167]
### Before reporting

- [X] I have tested with the lastest _master_

### Describe the bug

When navigating to a details view for a movie or tv-series with only a miniscule cast the grid is built from the left, which places the card all the way at the left side of the screen. This looks weird.

Either build all grids on details views from the center or do it when there are only a few results. 

### To Reproduce

Go to https://streamchaser.tv/tv/51015
See cast

### Expected behavior

Only one cast member is shown

**Comment by AndreasPB** [comment]
Clean-up closing - If it was a big problem I hope we would have done it by now 🙈
