### ISSUE TITLE
Fix 'Do not use --platform flag with FROM' issue in backend\Dockerfile

### ISSUE THREAD

**Issue by AndreasPB** [streamchaser/streamchaser#173]
[CodeFactor](https://www.codefactor.io/repository/github/streamchaser/streamchaser) found an issue: Do not use --platform flag with FROM

It's currently on:
[backend\Dockerfile:4](https://www.codefactor.io/repository/github/streamchaser/streamchaser/source/master/backend/Dockerfile#L4)
Commit 887f0ad062812ee4d229521c5daeffec1acb0783

**Comment by nullxDEADBEEF** [comment]
Isnt this fixed?

**Comment by AndreasPB** [comment]
@nullxDEADBEEF 
Yep, in #444
