### ISSUE TITLE
blacklist.txt not being used

### ISSUE THREAD

**Issue by Primdahl26** [streamchaser/streamchaser#183]
### Before reporting

- [X] I have tested with the lastest _master_

### Describe the bug

Right now all the logic with `blacklist.txt` is dead since we changed from where the program sees itself. Also meilisearch does not use the blacklist.txt.

### To Reproduce

1. try to remove and blacklist something
2. See that it did not add to the blacklist

### Expected behavior

It should use the blacklist.txt in meiliesearch and the remove-and-blacklist step

**Comment by AndreasPB** [comment]
Just tested with a print and it does print out the ids from the file, so I dont think it has anything to do with the `WORKDIR`
```python
@app.command()
def remove_blacklisted_from_search():
    blacklisted_media = [line.rstrip() for line in open("blacklist.txt")]
    print(blacklisted_media[:5])  # ['t118578', 't53347', 't77063', 't95600', 't77625']
    ...
```

**Comment by nullxDEADBEEF** [comment]
Not relevant anymore.
