### ISSUE TITLE
Optimize image sizes

### ISSUE THREAD

**Issue by AndreasPB** [streamchaser/streamchaser#204]
### Is your feature request related to a problem? Please describe.

The site is pretty hard to use on a bad connection

### Describe the solution you'd like

I'd like the images to be optimized for sizes they are used for. I'm not sure if we will have to do some view-port magic or not

We should be able to get some quick wins by just using smaller sizes

A forum post describing the possibilities: https://www.themoviedb.org/talk/53c11d4ec3a3684cf4006400

**Comment by nullxDEADBEEF** [comment]
#103
