### ISSUE TITLE
Cronjob failing some nights

### ISSUE THREAD

**Issue by Primdahl26** [streamchaser/streamchaser#215]
### Before reporting

- [X] I have tested with the lastest _master_

### Describe the bug

Some nights the cron job fails. We need to find out why.

<img width="876" alt="image" src="https://user-images.githubusercontent.com/50198099/165491945-fb889bff-b580-4024-a72b-589a02116374.png">

### To Reproduce

Go to grafana and look back at the nightly jobs

### Expected behavior

Every job should be succesful

**Comment by AndreasPB** [comment]
Should be fixed when #238 and #222 are merged
