### ISSUE TITLE
Setup dependabot

### ISSUE THREAD

**Issue by AndreasPB** [streamchaser/streamchaser#229]
### Is your feature request related to a problem? Please describe.

A lot of our dependencies are falling behind

### Describe the solution you'd like

A "not too aggressive" dependabot-setup

https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/

**Comment by Primdahl26** [comment]
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates

**Comment by nullxDEADBEEF** [comment]
Initial dependabot setup https://github.com/streamchaser/streamchaser/pull/321

**Comment by nullxDEADBEEF** [comment]
This was done in #464 closing.
