### ISSUE TITLE
Only reindex newly updated media

### ISSUE THREAD

**Issue by nullxDEADBEEF** [streamchaser/streamchaser#230]
### Is your feature request related to a problem? Please describe.

Right now when we update recently changed media, Meilisearch has to reindex all of the content which is unnecessary.

### Describe the solution you'd like

I want to only index the recently changed media, to do that, we can use the `updated_at` column of the db media.

**Comment by AndreasPB** [comment]
Currently not possible because of TMDB not updating their changed timestamp when the JustWatch dataset changes
