### ISSUE TITLE
Using "/" in search field freezes site (refresh needed)

### ISSUE THREAD

**Issue by Niklasbrock** [streamchaser/streamchaser#236]
### Before reporting

- [X] I have tested with the lastest _master_

### Describe the bug

Whenever a "/" is used in the search field, no results appear, and clicking any link will not result in page change, only url change.

### To Reproduce

1. Type "/" in search field at any time.

### Expected behavior

Page freeze

**Comment by nullxDEADBEEF** [comment]
Nice catch! 

We'll fix that ASAP :rocket: :eyes:

**Comment by Primdahl26** [comment]
<img src="https://media0.giphy.com/media/ziUFAwsjyZ3qPOXc7P/giphy.gif"/>

**Comment by Primdahl26** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/raw
