### ISSUE TITLE
Investigate/Make go projects use HTTP2

### ISSUE THREAD

**Issue by nullxDEADBEEF** [streamchaser/streamchaser#309]
### Is your feature request related to a problem? Please describe.

Right now our Go projects are using HTTP 1.1 could be fun to investigate if its possible for us to use http2 on the projects

### Describe the solution you'd like

Change our Go projects to use HTTP2

**Comment by AndreasPB** [comment]
We might already be using it, but if like someone else to read the docs as well: https://golang.google.cn/pkg/net/http/

> Starting with Go 1.6, the http package has transparent support for the HTTP/2 protocol when using HTTPS. Programs that must disable HTTP/2 can do so by setting...

And

> The http package's Transport and Server both automatically enable HTTP/2 support for simple configurations

**Comment by AndreasPB** [comment]
Go backend is no more 🕯️ The Python backend is already move to HTTP/2

I don't think it's gonna do much for the internal service
