### ISSUE TITLE
Try gRPC/tRPC

### ISSUE THREAD

**Issue by AndreasPB** [streamchaser/streamchaser#310]
### Is your feature request related to a problem? Please describe.

I think gRPC would make sense for a lot of things in our stack(especially the internal Go service)

Supposedly it is quite a bit faster than REST and got easy control of streaming(ez TQDM loading bars) 🐎 🚤 

tRPC or gRPC-WEB could also be cool to try for the frontend

### Describe the solution you'd like

Test how it feels to migrate or make something new with gRPC

### Additional context

https://github.com/icflorescu/trpc-sveltekit
https://grpc.io/
https://youtu.be/Yw4rkaTc0f8

**Comment by Pankai222** [comment]
<img src="https://media2.giphy.com/media/13t2W0dMRqGRZS/giphy.gif"/>

**Comment by AndreasPB** [comment]
This isn't being prioritized anymore, since it would be a huge rework for a limited amount of gain. It would also add more complexity, which we already have quite a lot of(for such a small scope/project).

I still think the idea of it is great, but I think just sticking to REST(but pushing HTTP/2) will make the project a lot more straightforward to work with.

**Comment by AndreasPB** [comment]
What was said above
