### ISSUE TITLE
Fix E2E tests for details 

### ISSUE THREAD

**Issue by Pankai222** [streamchaser/streamchaser#313]
### Before reporting

- [X] I have tested with the lastest _master_

### Describe the bug

After moving loading of data to page.ts tests targeting details-pages no longer work

![image](https://user-images.githubusercontent.com/48592277/200081112-46cabea5-1def-4e7e-a135-ae1b6cab039d.png)

### To Reproduce

1. Create pull request
2. Wait for 'frontend-build-and-test'-action to run
3. Watch it fail

### Expected behavior

The E2E test should pass

### Additional context

If you got the time you could add some extra E2E tests for that sweet feeling of additional test coverage

**Comment by AndreasPB** [comment]
The test has been been commented out with a reference to this issue https://github.com/streamchaser/streamchaser/blob/94d9a66afd9cb18e1d70b70f661878defb7d2565/frontend/tests/movie.spec.ts#L3
