### ISSUE TITLE
Theme selector is confusing SEO

### ISSUE THREAD

**Issue by AndreasPB** [streamchaser/streamchaser#323]
### Before reporting

- [X] I have tested with the lastest _master_

### Describe the bug

The "links" aren't crawlable... We should really stop using a-tags for things that aren't links :p

![image](https://user-images.githubusercontent.com/43907402/200964749-3eba621d-0c3e-41a7-b552-b0cdf55de318.png)

### To Reproduce

1. Run Lighthouse
2. Scroll to the SEO section

### Expected behavior

The crawlers shouldn't recognize the menu as a group of links

**Comment by Primdahl26** [comment]
Should be fixed after #328  was merged
