### ISSUE TITLE
Improve search for movies containing characters like '&'

### ISSUE THREAD

**Issue by Pankai222** [streamchaser/streamchaser#334]
### Is your feature request related to a problem? Please describe.

'And' is not treated as '&' when searching for movies containing '&'
![image](https://user-images.githubusercontent.com/48592277/201355204-4124191c-8987-4ee9-b7d3-2dc675c66368.png)

### Describe the solution you'd like

Use MeiliSearch alias to treat 'and' as '&'

**Comment by AndreasPB** [comment]
https://docs.meilisearch.com/learn/configuration/settings.html#synonyms
