### ISSUE TITLE
Search with even more parameters! (everything you got)

### ISSUE THREAD

**Issue by Niklasbrock** [streamchaser/streamchaser#428]
### Is your feature request related to a problem? Please describe.

Not being able to search for a production company, or just other things related to movies than their names.
The app is so fast that you want to explore with it, but it's so limited. 

### Describe the solution you'd like

If the data is in the API call, then you could add it alongside searching by actors. 

It's not high prio or anything, but I just wanted to search for "Studio Ghibli" to see all the animated movies by them. It just felt natural to do. So it might be worth adding at some point.

Imagine being able to search for "1980" and then movies from the year show up, in order of popularity. 
More search parameters would be awesome.

**Comment by AndreasPB** [comment]
I don't think we can implement this by using the main search field - It would have to be a filter to not have a million seemingly unrelated results show up at all times

Feel free to reopen if you wanna discuss ways of implementing something similar
