### ISSUE TITLE
Add a search option to the detail pages

### ISSUE THREAD

**Issue by sanders41** [streamchaser/streamchaser#557]
### Is your feature request related to a problem? Please describe.

When you perform a search then click on a card, there is no option to start a new search from the page you are redirected to. Instead you have to go back to the home page by clicking the streamchaser icon in the nav bar to do a new search. This works, but it always catches at first that I have to do it this way.

### Describe the solution you'd like

Add a search box in the nav bar once you leave the home page. An alternative would be a search link (maybe a magnifying glass?) in the search bar that takes you back to the home page for a new search to make it obvious that is how it works.

### Describe alternatives you've considered

Leave things as they are, it works as is.

**Comment by AndreasPB** [comment]
Great idea! This is something we have discussed on and off, but we could never decide on the proper implementation.

Would a select in the navbar work? Similar to our providers and genres, but using the MeiliSearch data (we should be able to have a low res poster on there as well) 
![billede](https://github.com/streamchaser/streamchaser/assets/43907402/c6f76472-3835-4729-ac9d-3a9aa38aa255)

Our select component [svelte-select](https://github.com/rob-balfre/svelte-select) has this in [one of their demos](https://svelte.dev/repl/3df87e32340e4e9e85bf371becae2af0?version=4.0.1), which could work:
![billede](https://github.com/streamchaser/streamchaser/assets/43907402/d9894bf3-1f3f-4906-99f9-d3a68c0b5583)

**Comment by sanders41** [comment]
I like the idea of putting it in the nav bar. 

I can't find an example right now, but I'm pretty sure I have seen times where more than one show/move has the same name. If I am remembering correctly when this happens usually one is available in the US and the other is not. With that, if it is possible to get the low res image in there to tell the apart it would be nice. But that is rare, so even without the image the search from the nav bar would be nice.

**Comment by Primdahl26** [comment]
@sanders41 i have tried putting it in the navbar, if the screen is wider than `1100px`. It can be tested [here](https://streamchaser-git-addsearchinnavbarandupdate-5648db-streamchaser.vercel.app), does it look fine?

**Comment by sanders41** [comment]
Looks good to me!

**Comment by AndreasPB** [comment]
The changes are live in production now! :)

Thanks for suggesting the feature, @sanders41!
